### ISSUE TITLE
PDF Export errors, log doesn't show what's wrong on my end

### ISSUE THREAD

**Issue by rioforce** [piersdeseilligny/betterfountain#212]
I have a supposedly 48 page screenplay, according to the statistics provided by Better Fountain, but upon trying to export PDF, I can't get anything. I'm running version 1.13.0. I looked in the logs and found this log any time I try to export PDF:

```
[2024-03-05 21:18:54.034] [exthost] [error] TypeError: Cannot read property 'toString' of undefined
	at hl.getCommonProperties (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\node_modules\vscode-extension-telemetry\lib\telemetryReporter.node.min.js:10:10855)
	at hl.sendTelemetryEvent (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\node_modules\vscode-extension-telemetry\lib\telemetryReporter.node.min.js:10:12222)
	at Object.reportTelemetry (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\telemetry.js:9:18)
	at c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:159:19
	at Generator.next (<anonymous>)
	at c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:4:12)
	at exportPdf (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:153:12)
	at c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:240:146
	at Generator.next (<anonymous>)
	at c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:4:12)
	at c:\Users\Benjamin\.vscode\extensions\piersdeseilligny.betterfountain-1.8.11\out\extension.js:240:92
	at b._executeContributedCommand (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88517)
	at b.$executeContributedCommand (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88849)
	at p._doInvokeHandler (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8638)
	at p._receiveOneMessage (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (c:\Users\Benjamin\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:483:12)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23) fountain.exportpdf
```

Exporting at HTML works fine, but of course, has no page breaks and isn't a PDF file, so it won't work for me. I can't figure any place in this log that shows me the syntax issues with my specific script, though (if I accidentally have a character missing, or am missing a specific line that I need for it to work, or if I'm required to have a title-page, etc). Is this diagnoseable?

Thanks!

**Comment by rioforce** [comment]
I'm sorry, I'm a dunce (and I can't figure out how to delete issues after I post them). I just needed to update VSCode. 😓

**Comment by piersdeseilligny** [comment]
no prob haha glad it's sorted
