### ISSUE TITLE
Option "Double the space between scenes" breaks live preview

### ISSUE THREAD

**Issue by belzecue** [piersdeseilligny/betterfountain#28]
Repro:

1. Confirm screenplay live preview is working for a fountain file.
2. Change setting "double the space between scenes" to ON.
3. Regenerate live preview.  Preview now broken.
4. Reset the option to OFF.
5. Regenerate live preview.  Preview now working again.

Sample log error output when broken:

`[2019-04-30 17:08:40.167] [exthost] [info] extension host started
[2019-04-30 17:08:40.190] [exthost] [info] ExtensionService#_doActivateExtension piersdeseilligny.betterfountain {"startup":false,"activationEvent":"onLanguage:fountain"}
[2019-04-30 17:08:40.190] [exthost] [info] ExtensionService#loadCommonJSModule C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.0\out\extension
[2019-04-30 17:08:40.827] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"activationEvent":"*"}
[2019-04-30 17:08:40.827] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\debug-auto-launch\dist\extension
[2019-04-30 17:08:40.831] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"activationEvent":"*"}
[2019-04-30 17:08:40.831] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\emmet\dist\extension
[2019-04-30 17:08:40.837] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"activationEvent":"*"}
[2019-04-30 17:08:40.837] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\git\dist\main
[2019-04-30 17:08:40.862] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"activationEvent":"*"}
[2019-04-30 17:08:40.862] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\merge-conflict\dist\extension
[2019-04-30 17:08:40.868] [exthost] [info] eager extensions activated
[2019-04-30 17:08:41.108] [exthost] [error] [piersdeseilligny.betterfountain] provider FAILED
[2019-04-30 17:08:41.111] [exthost] [error] TypeError: Cannot read property 'length' of undefined
	at GetFullRanges (C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.0\out\extension.js:526:48)
	at MyFoldingRangeProvider.provideFoldingRanges (C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.0\out\extension.js:558:18)
	at define.provideFoldingRanges.a.asPromise (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:505)
	at t.asPromise.Promise (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:430)
	at new Promise ()
	at Object.t.asPromise (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:49:402)
	at H.provideFoldingRanges (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:596:476)
	at define.$provideFoldingRanges._withAdapter.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:608:467)
	at B._withAdapter (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:599:159)
	at B.$provideFoldingRanges (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:608:445)
	at d._doInvokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:341)
	at d._receiveOneMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor.socketDisposables.push.socketReader.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor.register.socket.onData.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (streamreadable.js:279:12)
	at readableAddChunk (streamreadable.js:264:11)
	at Socket.Readable.push (streamreadable.js:219:10)
	at Pipe.onread (net.js:636:20)
[2019-04-30 17:11:00.690] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-04-30 17:11:00.690] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\configuration-editing\dist\extension
[2019-04-30 17:11:00.696] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-04-30 17:11:00.696] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\json-language-features\client\dist\jsonMain
[2019-04-30 17:11:00.712] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"activationEvent":"onLanguage:jsonc"}
[2019-04-30 17:11:00.712] [exthost] [info] ExtensionService#loadCommonJSModule c:\Andrew\Utility\VisualStudioCode\resources\app\extensions\typescript-language-features\dist\extension
[2019-04-30 17:11:13.298] [exthost] [error] TypeError: current_token.is is not a function
	at Object.exports.parse (C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.0\out\afterwriting-parser.js:446:66)
	at context.subscriptions.push.vscode.commands.registerCommand (C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.0\out\extension.js:245:34)
	at d._executeContributedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:621)
	at d.$executeContributedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:478:6)
	at d._doInvokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor.socketDisposables.push.socketReader.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor.register.socket.onData.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (streamreadable.js:279:12)
	at readableAddChunk (streamreadable.js:264:11)
	at Socket.Readable.push (streamreadable.js:219:10)
	at Pipe.onread (net.js:636:20) fountain.livepreview`

**Comment by piersdeseilligny** [comment]
Fixed in 1.3.1 (currently in the store)
