### ISSUE TITLE
Error: Illegal value for 'line'

### ISSUE THREAD

**Issue by belzecue** [piersdeseilligny/betterfountain#29]
Clicking on Outline headers causes error.

Demo:
https://i.imgur.com/xQYl6If.gif

Win10, VSC 1.33.1.

Log:

[2019-05-01 10:37:17.244] [exthost] [error] Error: Illegal value for `line`
	at u._lineAt (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:356:54)
	at Object.lineAt (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:355:13)
	at context.subscriptions.push.vscode.commands.registerCommand (C:\Users\migsdaf\.vscode\extensions\piersdeseilligny.betterfountain-1.3.1\out\extension.js:251:37)
	at d._executeContributedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:621)
	at d.executeCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:476:936)
	at f._executeConvertedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:479:133)
	at d._executeContributedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:477:621)
	at d.$executeContributedCommand (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:478:6)
	at d._doInvokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:622:11)
	at d._invokeHandler (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:621:716)
	at d._receiveRequest (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:620:394)
	at d._receiveOneMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:619:141)
	at define.constructor._protocol.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:617:400)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:40:460)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at a (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:467)
	at e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:172:513)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at y._receiveMessage (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:276)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:415)
	at u.fire (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:44:708)
	at f.acceptChunk (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:175:35)
	at define.constructor._register._socket.onData.e (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:174:410)
	at Socket.t (c:\Andrew\Utility\VisualStudioCode\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:689)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20) fountain.jumpto

**Comment by piersdeseilligny** [comment]
This only seems to occur when the currently focused document inside vscode is not the `.fountain` file (even just the screenplay preview). However obviously this is still a bug, which will be fixed.
